Repository AdoongE/FE, pull requests merged in 2024-11, with the labels that each got.

#6 Feat: 사이드바 UI
  package.json
  src/App.js
  src/assets/icons/bookmark.png
  src/assets/icons/file-plus.png
  src/assets/icons/forest.png
  src/assets/icons/grid.png
  src/assets/icons/seed.png
  src/assets/icons/tree.png
  src/components/Sidebar.js
  src/routes/router.js
  src/styles/GlobalStyle.js
  yarn.lock
Labels: Feature ✨

#5 Docs: issue templates 수정
  .github/ISSUE_TEMPLATE/custom.md
Labels: 📝 Docs

#7 Feat: 콘텐츠 화면 구현
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/custom.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  package.json
  public/index.html
  public/seed.png
  src/components/ContentBlank.js
  src/components/ContentBox.js
  src/components/ContentHeader.js
  src/components/dropdown/ContentDropdown.js
  src/components/modal/ContentDeleteModal.js
  src/pages/MainPage.js
  src/routes/Router.js
  src/styles/GlobalStyle.js
  yarn.lock
Labels: Feature ✨

#20 Feat: 카테고리 추가 모달 파일 분리
  package.json
  src/components/Navbar.js
  src/components/Sidebar.js
  src/components/modal/AddCategoryModal.js
Labels: 📝 Docs

#24 Feat/initial contents add #13
  package.json
  src/assets/icons/Check.png
  src/components/InitialContentAdd.js
  src/pages/ContentAddPage.js
  src/routes/Router.js
  yarn.lock
Labels: Feature ✨

#29 Feat: 콘텐츠 생성 컴포넌트 합치기
  src/components/InitialContentAdd.js
  src/components/modal/AddCategoryModal.js
  src/components/modal/RemoveCategoryModal.js
  src/pages/ContentAddPage.js
Labels: Feature ✨

#34 콘텐츠 생성 컴포넌트 연결
  src/components/AddContent.js
  src/components/ImageUpload.js
  src/components/InitialContentAdd.js
  src/components/LinkUploader.js
  src/components/Navbar.js
  src/components/PdfUpload.js
  src/components/api/ContentAddApi.js
  src/components/api/KakaoRedirect.js
  src/components/api/SignUpApi.js
  src/components/modal/AddLinkModal.js
  src/components/modal/AddTagModal.js
  src/components/modal/ContentSaveModal.js
  src/index.js
  src/pages/ContentAddPage.js
  src/routes/Router.js
Labels: Feature ✨

#37 Feat: 콘텐츠 상세 조회 구현, API 연동 #30
  src/assets/icons/logo.png
  src/components/ViewContent.js
  src/components/modal/LoginModal.js
  src/pages/ContentViewPage.js
  src/routes/Router.js
Labels: Feature ✨

#40 콘텐츠 생성 링크/모달 초기화 기능 수정
  src/components/AddContent.js
  src/components/modal/AddLinkModal.js
  src/components/modal/AddTagModal.js
  src/components/modal/ContentSaveModal.js
Labels: Feature ✨

#52 콘텐츠 addContent 파일 병합/api 수정
  src/components/AddContent.js
  src/components/ContentBox.js
  src/components/LinkUploader.js
  src/components/Sidebar_api.js
  src/components/ViewContent.js
  src/components/api/ContentAddApi.js
  src/components/bar/SplashBar.js
  src/components/dropdown/AddCategoryDropdown.js
  src/components/dropdown/ContentDropdown.js
  src/components/modal/AddLinkModal.js
  src/components/modal/ContentDeleteModal.js
Labels: Feature ✨

#66 콘텐츠 생성 유효성 및 기타 오류 수정
  src/components/AddContent.js
  src/components/LinkUploader.js
  src/components/Navbar.js
  src/components/modal/AddLinkModal.js
  src/components/modal/AddTagModal.js
  src/components/modal/ContentSaveModal.js
  src/components/modal/NewAddCategoryModal.js
Labels: Bug 🐞
